zeta-chain/node

.github/workflows/build.yml
.github/workflows/deploy.yml
.github/workflows/gosec.yml
.github/workflows/linter.yml

Disabled buildjet runners to work-around problems caused when we open sourced the repo and changed the name. 

fix: disabled buildjet runners

---

.github/actions/build-docker-images/action.yml

updated docker build action to include buildx env.

fix: add buildx to docker builds

---

.github/actions/build-docker-images/action.yml
.github/workflows/build.yml

fixing upload step with docker build kit.

build: fix

---

.gitignore
zetaclient/btc_signer.go

1. Update the estimated fee to 10,000 satoshi
2. Refactor the SignWithdrawTx call with the gasPrice

fix: increased fee to 10000 stat and used gasPrice for fee calculation

---

.gitignore
zetaclient/btc_signer.go

fix: enforced minFee

---

zetaclient/bitcoin_client.go
zetaclient/btc_signer.go
zetaclient/btc_test.go
zetaclient/btc_util.go
zetaclient/telemetry.go
zetaclient/types/sql_btc.go
zetaclient/types/telemetry_types.go

Cleaned up the pending UTXO logic.

fix: cleaned up pending utxo

---

x/crosschain/keeper/keeper_cross_chain_tx.go

fix: expand CctxAllPending query RPC to include pending cctxs below NonceLow

---

zetaclient/evm_client.go
zetaclient/evm_signer.go

Fixing crashes on zetaclient due to nil references and malformed data in database.

fix: Hot fix v5.0.2

---

.github/workflows/node-operations-athens3.yml

Some fixes to the node operations action. This is temporary and the action will be moved to the infrastructure repo soon. 

fix: ci - fixed inputs and increased restart time to 90 seconds per region

---

.github/workflows/build.yml

Fixed ci concurrency restriction that failed for events other than PRs/  

fix: ci concurrency error

---

.github/workflows/build.yml

Updated the discord message to be shorter inside of the build.yml file.
Just updated the discord message inside the build.yml file to be shorter.

ci: update discord message in build.yml

---

zetaclient/bitcoin_client.go
zetaclient/telemetry.go
zetaclient/types/telemetry_types.go

1. Cleaned up nonce in Bitcoin client and TelemetryServer
2. Cleaned up persistence of includedTx in Bitcoin client

fix: removed nonce and persistence of includedTx

---

.github/workflows/build.yml

Trying to fix intermittent build failure for alpine job. 

ci: Fixing alpine build-test failure 

---

x/crosschain/genesis.go
x/crosschain/module.go
x/crosschain/types/genesis.go
x/emissions/genesis.go
x/emissions/module.go
x/emissions/types/genesis.go
x/fungible/genesis.go
x/fungible/module.go
x/fungible/types/genesis.go
x/observer/genesis.go
x/observer/module.go
x/observer/types/genesis.go

Rename in comment the usage of `capability` into the corresponding module name

docs: fix module name in comments

---

app/setup_handlers.go

chore: update handler version

---

go.mod
go.sum

fix: use new contracts

---

app/setup_handlers.go
x/observer/keeper/params.go

add maturity blocks for ballots

---

cmd/zetaclientd/aux.go
cmd/zetaclientd/keygen_tss.go
cmd/zetaclientd/start.go
standalone-network/gov/gov_observer_params_supported_chains.json
x/crosschain/client/cli/query_get_tss_address.go
zetaclient/config/types.go
zetaclient/query.go
zetaclient/zetabridge.go

fix: v9.0.1

---

cmd/zetaclientd/init.go
common/default_chains_mainnet.go
common/default_chains_mock_mainnet.go
common/default_chains_privnet.go
common/default_chains_testnet.go
standalone-network/run-zetaclient.sh
x/observer/types/core_params_mainnet.go
x/observer/types/core_params_mock_mainnet.go
x/observer/types/core_params_privnet.go
x/observer/types/core_params_testnet.go
zetaclient/config/config_mainnet.go
zetaclient/config/config_mock_mainnet.go
zetaclient/config/config_privnet.go
zetaclient/config/config_testnet.go
zetaclient/query.go
zetaclient/zetabridge.go

remove zetachain from config

---

go.mod
go.sum
x/crosschain/keeper/keeper_cross_chain_tx_vote_inbound_tx.go
x/crosschain/keeper/keeper_in_tx_tracker.go
zetaclient/bitcoin_client.go
zetaclient/evm_client.go
zetaclient/inbound_tracker.go
zetaclient/inbound_tracker_test.go
zetaclient/query.go
zetaclient/tx.go
zetaclient/utils.go

feat: zetaclient read logs functions

---

app/setup_handlers.go

chore: increment handler version

---

x/fungible/keeper/begin_blocker_deploy_system_contracts_mock_mainnet.go

fix: begin blocker for mock mainnet

---

zetaclient/evm_client.go
zetaclient/evm_signer.go

Report failed ERC20 transfers from TSS. This should not happen, but should be reported. 

fix(`zetaclient`): report failed ERC20 transfers from TSS

---

readme.md

This is a note regarding the code freeze for our repository

docs: code freeze note

---

.goreleaser.yaml
changelog.md

Sync with change on branch `v11.0.0`

chore: remove build types in `.goreleaser.yaml`

---

changelog.md

Add `v11.0.0` section in changelogs and add remaining changes in unreleased

docs: resync changelogs with v11.0.0

---

go.mod
go.sum

Updated the ledger dependencies so it works with the latest version of OSX 14.2.1.

chore: update ledger dependencies

---

changelog.md
x/observer/types/chain_params.go
x/observer/types/chain_params_test.go
zetaclient/zetacore_observer.go

The chain params were updated every time because the comparison check was not correct.

fix(`zetaclient`): fix chain params comparison logic

---

changelog.md
readme.md

Updated release instructions to make clear internal testing use vs public release based on feedback from external validators and our developments. 

docs: updated release instructions

---

.github/workflows/publish-release.yml
.github/workflows/rc-release.yml
changelog.md

fix: fix the cleanup step in the rc-release and publish-release pipelines
Closes: No-Ticket-Adhoc-Fix

ci: fix the cleanup step in the rc-release and publish-release pipelines

---

changelog.md
docs/cli/zetacored/zetacored_query_observer_get-historical-tss-address.md
docs/cli/zetacored/zetacored_query_observer_get-tss-address.md
x/observer/client/cli/query_get_tss_address.go

- add bitcoin chain id to `get tss address` and `get tss address historical` cli query

fix: get tss address cli

---

changelog.md
zetaclient/btc_signer.go
zetaclient/zetacore_observer.go

Closes: [1656](https://github.com/zeta-chain/node/issues/1656)

fix: schedule bitcoin keysign with intervals to avoid keysign failures (took hours)

---

changelog.md
x/crosschain/keeper/grpc_query_zeta_conversion_rate.go

fix: remove the unnecessary multiplier in the convertGasToZeta RPC

---

changelog.md
docs/openapi/openapi.swagger.yaml
scripts/protoc-gen-openapi.sh

chore: add Ethermint endpoints to OpenAPI

---

app/setup_handlers.go

chore: update the setup handler

---

changelog.md
zetaclient/evm/evm_client.go
zetaclient/evm/evm_client_test.go

partially Closes: [1678](https://github.com/zeta-chain/node/issues/1678)

fix: evm outtx hash mismatch

---

changelog.md

Put `v14` cahngelog at the right place

chore: fix v14 changelog

---

.github/workflows/docker-build-and-push.yml
changelog.md

Fix docker repo typo.
No need to test this.

ci: fix docker repo typo

---

common/ethereum/proof_test.go
testutil/sample/common.go
x/crosschain/keeper/msg_server_add_to_intx_tracker_test.go
x/crosschain/keeper/msg_server_add_to_outtx_tracker_test.go
x/observer/keeper/msg_server_add_block_header_test.go

These tests are invalid and commented out

test:comment out tests using goerli endpoint

---

.github/workflows/build.yml
.github/workflows/publish-release.yml
.github/workflows/rc-release.yml
changelog.md

ci: update build runner for publish release to github actions ubuntu 20.04 runners.
Closes: ADHOC
This is a fix for a current issue.

ci: update build runner for publish release to github actions ubuntu 20.04 runners.

---

x/crosschain/keeper/refund.go
x/lightclient/types/block_header_verification.go
zetaclient/chains/bitcoin/observer/observer.go

chore: fix some function names

---

changelog.md

Synchronize the v17 changelogs on `develop` branch

chore: synchronize v17 changelogs

---

.github/ISSUE_TEMPLATE/syncing.yaml

* phrasing
* removed state sync as we no longer support it

ci: phrasing in the syncing template

---

.github/workflows/e2e.yml

Backport https://github.com/zeta-chain/node/pull/2580

fix(ci): correct slack conditional comparison (backport)

---

.github/workflows/e2e.yml

fix(ci): propagate timeout-minutes (#2583)

---

changelog.md

Backport 8d592ca0f2b982c4a25bd6f4a98afcc4d3a332ba to release branch

chore: backport v19 changelogs update

---

changelog.md
zetaclient/orchestrator/orchestrator.go

fix: hardcode schedule interval

---

changelog.md
zetaclient/orchestrator/orchestrator.go

fix: move interval assignment out of cctx loop

---

go.mod
go.sum
zetaclient/orchestrator/orchestrator.go

https://github.com/zeta-chain/go-tss/pull/27
https://github.com/zeta-chain/node/pull/2849

fix: update go-tss with known fixes (v19)

---

go.mod
go.sum

https://github.com/zeta-chain/go-tss/pull/27

fix: update go-tss with known fixes (v19.1)

---

go.mod
go.sum

https://github.com/zeta-chain/node/pull/2849

fix: update go-tss with known fixes (release v20)

---

app/encoding.go
zetaclient/chains/evm/observer/observer.go
zetaclient/chains/evm/observer/observer_test.go
zetaclient/chains/evm/signer/signer_test.go
zetaclient/orchestrator/bootstrap.go

https://github.com/zeta-chain/node/pull/2834
https://github.com/zeta-chain/node/pull/2828

chore: backport more fixes for v20

---

e2e/runner/v2_migration.go
zetaclient/chains/bitcoin/observer/inbound.go
zetaclient/chains/bitcoin/observer/inbound_test.go

fix: add Solana ZRC20 in v2 migration test (v20)

---

pkg/ticker/ticker.go
pkg/ticker/ticker_test.go
x/crosschain/keeper/grpc_query_cctx.go
x/crosschain/keeper/grpc_query_cctx_test.go
zetaclient/chains/evm/observer/observer.go

- https://github.com/zeta-chain/node/pull/2871
- https://github.com/zeta-chain/node/pull/2882
- https://github.com/zeta-chain/node/pull/2881

chore: backport changes for v20.0.2

---

go.mod
go.sum

use this go-tss branch: https://github.com/zeta-chain/go-tss/commits/v20-stop-dht-after-5min/

fix: stop dht after 5min

---

testutil/keeper/mocks/fungible/bank.go
x/fungible/keeper/deposits_test.go
x/fungible/keeper/zeta.go
x/fungible/keeper/zeta_test.go
x/fungible/keeper/zevm_message_passing_test.go
x/fungible/types/errors.go
x/fungible/types/expected_keepers.go

Add a check for ZETA deposit to not surpass a supply cap as an extra security check

refactor: improve ZETA deposit check with max supply check

---

cmd/zetae2e/local/local.go
precompiles/precompiles.go

To switch `release/v23` base branch once created

refactor: disable precompile for v23

---

cmd/zetacored/root.go
docs/cli/zetacored/cli.md

original PR: https://github.com/zeta-chain/node/pull/3470

fix: backport cmd fix

---

zetaclient/chains/bitcoin/bitcoin.go

Add the `OutboundScheduleInterval` check back when scheduling Bitcoin TSS keysign.

fix: add back bitcoin TSS keysign interval

---

contrib/localnet/scripts/start-upgrade-orchestrator.sh

Gas increased and log format changed with sdk v0.50.x base.
Will port to develop when we use v28 base.

chore: fix upgrade tests (v28)

---

zetaclient/chains/ton/config/config.go
zetaclient/chains/ton/config/config_test.go

Backport https://github.com/zeta-chain/node/pull/3586

fix(zetaclient): TON config resolution [backport]

---

changelog.md
cmd/zetaclientd/start.go
contrib/localnet/scripts/start-zetaclientd.sh
zetaclient/chains/bitcoin/observer/event_test.go
zetaclient/chains/evm/observer/inbound_test.go
zetaclient/chains/evm/observer/outbound_test.go
zetaclient/chains/solana/observer/inbound_test.go
zetaclient/compliance/compliance_test.go
zetaclient/config/config.go
zetaclient/config/types.go
zetaclient/types/event_test.go

Backport https://github.com/zeta-chain/node/pull/3600 and prepare v28.1.0

feat(zetaclient): add dedicated restricted addresses config file (#3600)

---

changelog.md
zetaclient/chains/base/observer.go
zetaclient/chains/base/observer_test.go
zetaclient/chains/evm/observer/inbound_test.go
zetaclient/chains/interfaces/interfaces.go
zetaclient/chains/sui/observer/observer_test.go
zetaclient/chains/ton/observer/inbound_test.go
zetaclient/chains/ton/observer/observer_test.go
zetaclient/testutils/mocks/zetacore_client.go
zetaclient/testutils/mocks/zetacore_client_opts.go

fix: backport(v29) check if cctx has already been created before casting inbound vote

---

changelog.md
go.mod
go.sum

Backport https://github.com/zeta-chain/node/pull/3702

fix: upgrade cosmos sdk to v0.50.13 (v28)

---

changelog.md
go.mod
go.sum

Backport https://github.com/zeta-chain/node/pull/3702

fix: upgrade cosmos sdk to v0.50.13 (v29)

---

changelog.md
go.mod
go.sum
zetaclient/chains/sui/sui.go
zetaclient/chains/ton/liteapi/client.go
zetaclient/chains/ton/observer/inbound.go
zetaclient/chains/ton/observer/observer.go
zetaclient/chains/ton/observer/outbound.go

feat: backport TON PRs

---

zetaclient/chains/evm/signer/gas.go

Fix related to https://github.com/zeta-chain/node/pull/3719
There was one condition missing in this fix: when reverting and calling onRevert from a gas deposit. The default gas limit for gas token 21k is used while the revert tx does a smart contract call, requiring a minimum value above 21k

fix(v29): improve the check for the gas limit patch

---

zetaclient/chains/evm/signer/gas.go

https://github.com/zeta-chain/node/pull/3732 backport to v28

fix(v28): improve the check for the gas limit patch

---

cmd/zetae2e/local/local.go
e2e/e2etests/e2etests.go
e2e/e2etests/test_solana_withdraw_and_call.go
e2e/e2etests/test_solana_withdraw_and_call_invalid_msg_encoding.go
e2e/e2etests/test_solana_withdraw_and_call_revert_with_call.go
e2e/e2etests/test_solana_withdraw_revert_executable_receiver.go
e2e/runner/solana.go
zetaclient/chains/evm/signer/gas.go
zetaclient/chains/evm/signer/gas_test.go
zetaclient/chains/solana/signer/execute.go
zetaclient/chains/solana/signer/execute_spl.go
zetaclient/chains/solana/signer/increment_nonce.go
zetaclient/chains/solana/signer/signer.go
zetaclient/chains/solana/signer/whitelist.go
zetaclient/chains/solana/signer/withdraw.go
zetaclient/chains/solana/signer/withdraw_spl.go

https://github.com/zeta-chain/node-patch/pull/11
https://github.com/zeta-chain/node-patch/pull/14
https://github.com/zeta-chain/node-patch/pull/17

fix: backport for v30 patches

---

cmd/zetae2e/local/local.go
e2e/e2etests/e2etests.go
e2e/e2etests/test_solana_withdraw_and_call.go
e2e/e2etests/test_solana_withdraw_and_call_invalid_msg_encoding.go
e2e/e2etests/test_solana_withdraw_and_call_revert_with_call.go
e2e/e2etests/test_solana_withdraw_revert_executable_receiver.go
e2e/runner/solana.go
zetaclient/chains/solana/signer/signer.go

https://github.com/zeta-chain/node-patch/pull/6
https://github.com/zeta-chain/node-patch/pull/7

fix: backport for v29 patches 

---

go.mod
go.sum

Related https://github.com/zeta-chain/go-tss/pull/61

feat(v30): bump go-tss

---

go.mod
go.sum

Cherry-pick https://github.com/zeta-chain/node/pull/3897

feat(ton): update tongo to v1.16.4

---

e2e/e2etests/test_bitcoin_deposit_invalid_memo_revert.go
zetaclient/chains/bitcoin/observer/inbound.go

Port [PR 4090](https://github.com/zeta-chain/node/pull/4090) to v34

fix: port Bitcoin memo decoding error log print to v34

---

pkg/errors/crosschain_error_message.go

Optimize code using a more modern writing style. Official support from Go, for more details visit https://pkg.go.dev/golang.org/x/tools/gopls/internal/analysis/modernize.

refactor: replace HasPrefix+TrimPrefix with CutPrefix
