zeta-chain/node

- readme.md
fix command to build for testnet.
> fix(doc): Update readme.md

- zetaclient/btc_signer.go
- zetaclient/btc_signer_test.go
- zetaclient/btc_test.go
Spending each UTXO requires one keysign, a bitcoin transaction might cause keysign timeouts if too many UTXOs are used as inputs. This PR enforces the maximum number of UTXOs check (<= 20 UTXOs) for BTC outbound transfers.
Closes: #773
> feat: enforce max number of UTXOs

- zetaclient/bitcoin_client.go
- zetaclient/btc_signer.go
- zetaclient/btc_signer_test.go
1. Modified current unit test cases and added new cases that cover the new "nonce-mark" utxos in "SelectUTXOs"
2. Avoid situations where accidental conflicts of nonce-mark UTXOs -- there might be cases when there were multiple nonce-mark UTXOs with the same nonce mark.
3. Made "SelectUTXOs" a method of bitcoin client to better control the access to unspent utxos to avoid potential race conditions when being accessed across threads.
4. To bootstrap nonce mark UTXO feature, we can manually send 0.00002 BTC to Tss and enable the TxID check in subsequent upgrade.
> feat: use nonce-mark UTXO to align TSS signers

- .github/workflows/chain-operations.yml
- .github/workflows/deploy.yml
Rename the "Chain Operations" action in the node repo to "node operations - Athens2
Rename "Deploy ZetaChain Update" to "Deploy ZetaChain Update - Athens2"
Changed the names for old Athens 2 Actions
> feat: ci - Rename old A2 Actions

- .github/workflows/build.yml
> ci: fix build test

- contrib/rpctest/main.go
- x/crosschain/client/querytests/intx_hash.go
- x/observer/client/querytests/permission_flags.go
- zetaclient/config/config_mainnet.go
Fix the issues raised by `gosec` in Lint CI
- Use `nosec` for test priv key definitions
- Remove usage of pointer reference in iterated values
> fix: `gosec` lint issues

- .github/workflows/build.yml
Added a conditional Docker Hub login step for the job to run in the build.yml when a PR is created from the zeta-chain/node repository, and does not require Docker Hub login when it is an external contributor.
> ci: Add conditional Docker Hub login step

- docs/openapi/openapi.swagger.yaml
- scripts/protoc-gen-openapi.sh
Downgraded to the version without this bug. We shouldn't be using `latest` anyway. We can upgrade manually once the underlying issue is resolved in `go-yaml`.
closes https://github.com/zeta-chain/node/issues/1078
> fix: generation of OpenAPI by downgrading a buf plugin

- zetaclient/utils.go
`zetaclient` treat 0-value unspent UTXO as invalid while bitcoin actually allows creating and sending `0-value` UTXO to receiver (TSS). Zetaclient had several `0-value` unspent UTXOs in its possession and was not able to spend them due to the wrong logic is wrong in `getSatoshis` function.
> fix: cherry pick v9.0.8 hotfix (fix Bitcoin amount verification)

- go.mod
- go.sum
Remove the fork that we used for `v8` bug
> chore: switch back to `cosmos/cosmos-sdk`

- zetaclient/bitcoin_client.go
Duplicate payment happened to bitcoin outbound nonce 0.
payment1: https://blockstream.info/tx/71395db26ae81147dd79176e394c598b9480036c5ef6e44608b3356283168872
payment2: https://blockstream.info/tx/26aa6b32b7f16cc6671ac1419e91bac5fb78b5d24536df0da0120a3f75bf9116
This PR is to special handle nonce 0 to avoid duplicate payments.
> fix: Mock mainnet begin block deployment fix btc duplicate payment

- zetaclient/btc_signer.go
Remove the division by 100 in bitcoin outTx fee calculation.
> fix: removed division by 1000 in fee calculation

- cmd/zetacored/main.go
- cmd/zetacored/root.go
Add a notice to quickly figure out the issue when using `--ledger` with default HD path.
I realized that injecting logic at runtime for an existing command is non-trivial without a fork or wrap (which we don't want for this fix).
I instead added a notice below the execution if the error is `cannot set custom bip32 path with ledge`
```
$zetacored keys add testledger --ledger --account 0
Error: cannot set custom bip32 path with ledger
Usage:
<appd> keys add <name> [flags]
Flags:
--account uint32           Account number for HD derivation (less than equal 2147483647)
--algo string              Key signing algorithm to generate keys for (default "eth_secp256k1")
--coin-type uint32         coin type number for HD derivation (default 118)
--dry-run                  Perform action, but don't add …
```
> fix(`cmd`): add notice when using `--ledger` with Ethereum HD path

- rpc/websockets.go
- x/emissions/client/tests/suite.go
- x/observer/module_simulation.go
Fix the new gosec issues in the CI
Using nosec for false positive.
Adding timeout for websocket server.
Need confirmation for the following values:
- read timeout - 15sec
- write timeout - 15sec
- idle timeout - 1 minute
Pinging @zeta-chain/devops in case
Closes: https://github.com/zeta-chain/node/issues/1288
> fix: gosec issues

- x/crosschain/keeper/keeper_cross_chain_tx_vote_outbound_tx.go
- x/crosschain/keeper/keeper_cross_chain_tx_vote_outbound_tx_test.go
Skip gas stability pool funding when gasLimit is equal gasUsed.
Closes: #1287 
> refactor: skip gas stability pool funding when gasLimit is equal gasUsed

- .dockerignore
- .github/workflows/publish-release.yml
- .goreleaser.yaml
Added mainnet builds to go releaser so binaries are available for testing only. 
Goreleaser has been tested in the CI-testing fork of the repo. Mainnet builds that have been added replicate the build flags in the Makefile and should work.
> ci: add mainnet builds to goreleaser

- common/address_test.go
- common/chain.go
- common/chain_test.go
Problem: currently when user withdraws assets from ZRC20, the withdraw event hooks validates
the `to` address that the user inputs.  However it failed to distinguish between bitcoin mainnet 
and testnet3 addresses. 
This PR fixes that validation logic so that a user cannot specify a wrong address on bitcoin network
without revering that withdraw transaction. 
> fix(`common`)!: bitcoin address validation to verify networks

- changelog.md
- zetaclient/evm_client.go
Cherry-picked code from branch hotfix-v10.1.4
> fix: speed up evm outtx inclusion and improve log prints

- app/app.go
- changelog.md
> fix: block `distribution` module account to receive ZETA

- changelog.md
- cmd/zetacored/main.go
I was attempting to set up my wallet on a ledger, and ran in to a wall. I misinterpreted the error message that was returned, and thought that text explicitly saying "do X to achieve Y" would be more clear.
> docs: Update the --ledger --hd-path hint for clarity

- changelog.md
- rpc/websockets.go
Closes: https://github.com/zeta-chain/security/issues/50
> fix(`rpc`): reduce websocket message limit to 10MB

- changelog.md
- x/crosschain/module.go
Change log level from Error to Info since the process is expected to return an error when gas stability pools are empty. This doesn't reflect an issue in the protocol itself.
Closes: https://github.com/zeta-chain/node/issues/1494
> refactor(`crosschain`): change log level for gas stability pool iteration error

- changelog.md
- zetaclient/bitcoin_client.go
- Screen out unconfirmed UTXOs that are not created by TSS to prevent DoS.
Closes: [48](https://github.com/zeta-chain/security/issues/48)
> fix: screen out unconfirmed utxos that are not created by TSS itself

- changelog.md
- x/observer/keeper/msg_server_update_crosschain_flags.go
- x/observer/keeper/msg_server_update_crosschain_flags_test.go
- x/observer/types/message_crosschain_flags.go
- x/observer/types/message_crosschain_flags_test.go
Related to https://github.com/zeta-chain/security/issues/53
> refactor(`MsgUpdateCrosschainFlags`): requires group2 policy type to enable header verification

- changelog.md
- x/crosschain/keeper/evm_hooks.go
Add a check for topic length
Closes: https://github.com/zeta-chain/security/issues/49
> fix(`crosschain`): add emptiness check for topic array in event parsing

- changelog.md
- zetaclient/btc_signer.go
- zetaclient/evm_client.go
- zetaclient/inbound_tracker.go
- zetaclient/utils.go
1. Includes a bug fix that relates to security. Inbound tracker tx hash needs to be checked against Tss address.
2. Some refactor work to better organize inTx vote message built/posting.
3. fix log printing
Closes: [1592](https://github.com/zeta-chain/node/issues/1592)
> fix: some necessary code refactor for banned address and bug fix during refactor

- Dockerfile-versioned-source
- Makefile
- app/setup_handlers.go
- changelog.md
Increment handler version to v12.1.0
> chore: increment hanlder to v12.1.0

- changelog.md
- cmd/zetaclientd/keygen_tss.go
- cmd/zetaclientd/start.go
- Allow zeta-client to start if keygen status is set to `PendingKeygen` and keygen block is `MaxInt64`
> fix: skip keygen loop

- changelog.md
- cmd/zetae2e/local/erc20.go
- contrib/localnet/scripts/start-zetaclientd-genesis.sh
- contrib/localnet/scripts/start-zetaclientd.sh
- zetaclient/bitcoin_client.go
- zetaclient/broadcast.go
- zetaclient/btc_signer.go
- zetaclient/evm_client.go
- zetaclient/inbound_tracker.go
- zetaclient/interfaces.go
- zetaclient/telemetry.go
- zetaclient/tx.go
- zetaclient/tx_vote_inbound.go
- zetaclient/tx_vote_outbound.go
- zetaclient/utils.go
- zetaclient/voter_test.go
- zetaclient/zetacore_observer_test.go
Cherry-pick the fixes, except:
- https://github.com/zeta-chain/node/commit/74f6a91adbb996ce45f7bda6c8ff5e814f0822af
- https://github.com/zeta-chain/node/commit/9d33b89062ce19a4d2e920e02792fb5e73d89183
> fix: cherry-pick ZetaClient fixes from `12.0.4`

- changelog.md
- common/coin.go
- common/coin_test.go
- x/emissions/abci.go
- x/emissions/abci_test.go
- x/emissions/client/tests/observer_rewards_test.go
- x/emissions/keeper/block_rewards_components.go
- x/emissions/keeper/block_rewards_components_test.go
- x/emissions/types/keys.go
- Replace dynamically calculated block rewards by fixed rewards 
- Add additional logs for mock mainnet deployment 
Closes : https://github.com/zeta-chain/node/issues/1660
> fix: modify emissions to follow fixed rewards per block

- changelog.md
- x/crosschain/keeper/msg_server_whitelist_erc20.go
Whitelisting ERC20 should be authorized to group2 only.
Closes: #1641 
> fix: change WhitelistERC20 authorization from group1=>group2

- changelog.md
- zetaclient/btc_signer.go
- zetaclient/btc_signer_test.go
- zetaclient/utils.go
1.  use estimated SegWit tx size for Bitcoin gas fee calculation
2. estimate SegWit tx size in uinit of vByte
see doc: https://github.com/bitcoin/bips/blob/master/bip-0141.mediawiki#transaction-size-calculations
3. increase depositor fee rate from `5 sats/vB` --> `20 sats/vB`
Closes: [1661](https://github.com/zeta-chain/node/issues/1661)
Closes: [1667](https://github.com/zeta-chain/node/issues/1667)
> fix: fix SegWit tx size estimation (in vByte) and gas fee calculation

- changelog.md
- zetaclient/broadcast.go
During busy time the block gas limit will be near full and as result, gas price can increase block by block due to EIP1559 -like feemarket. `zetaclientd` queries base gas price before making a tx, but the gas price might already be too low for the next block. This PR over pays 50% base gas price to buffer for such block gas price increases, targeting around 10min non-stop gas price increase. 
> fix: paying 50% more than base gas price to buffer EIP1559 gas price increase

- changelog.md
- x/crosschain/keeper/msg_server_add_to_outtx_tracker_test.go
- x/emissions/keeper/params.go
- x/emissions/keeper/params_test.go
- x/emissions/types/keys.go
- x/emissions/types/params.go
Returns the param values instead of new params for emissions module
Closes: <#1681>
> fix: fix emission params query and add unit tests

- server/config/config.go
json-rpc.allow-unprotected-txs is not take effect
Send a Pre-EIP-155 transction and will not get an error of `only replay-protected (EIP-155) transactions allowed over RPC`
> fix: json-rpc.allow-unprotected-txs

- changelog.md
- zetaclient/bitcoin_client.go
- zetaclient/inbound_tracker.go
- zetaclient/interfaces.go
- zetaclient/query.go
Closes: [1721](https://github.com/zeta-chain/node/issues/1721)
> fix: cherry pick hotfix v12.2.5

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/ISSUE_TEMPLATE/task.md
- changelog.md
Add templates for when creating issues.
The team will generally use task template.
Bugs and features give a framework for external for enquiries.
Closes: https://github.com/zeta-chain/node/issues/1726
> chore: add issue templates

- changelog.md
- cmd/zetaclientd/encrypt_tss.go
- cmd/zetaclientd/start.go
- go.mod
- go.sum
added cmd to encrypt tss keyshare file, allowing empty tss password for backward compatibility.
> feat: added cmd to encrypt tss keyshare file

- changelog.md
- x/crosschain/keeper/keeper.go
- x/crosschain/keeper/msg_server_gas_price_voter.go
- x/crosschain/keeper/msg_server_vote_inbound_tx_test.go
- Make staking keeper private 
- remove pointer receiver
> refactor: make staking keeper private

- Dockerfile-versioned-source
- app/setup_handlers.go
- changelog.md
Closes: https://github.com/zeta-chain/node/issues/1776
> chore: update upgrade handler to `v13`

- zetaclient/bitcoin/bitcoin_client.go
The current upgrade height `832000` has already past. We should offset the height to future. I increased the Bitcoin height by `2` more weeks.
> set mainnet btc deposit fee height to future height

- Makefile
- changelog.md
- codecov.yml
- testutil/network/genesis_state.go
- x/authority/types/message_update_policies_test.go
- x/authority/types/policies_test.go
- x/crosschain/keeper/evm_hooks_test.go
- x/emissions/abci_test.go
- x/observer/keeper/msg_server_remove_chain_params_test.go
- x/observer/keeper/nonce_to_cctx_test.go
- x/observer/keeper/nonces_test.go
- x/observer/keeper/observer_set_test.go
- x/observer/keeper/pending_nonces_test.go
- x/observer/keeper/tss_funds_migrator_test.go
- x/observer/keeper/tss_test.go
- x/observer/keeper/utils_test.go
Change `test-coverage` to make the command fail when unit test fails
Fix some failing unit tests.
This also fix the code coverage that went down because of missing directories.
> test: fix some failing unit tests

- changelog.md
- x/emissions/abci.go
- x/emissions/abci_test.go
- x/emissions/genesis_test.go
- x/emissions/keeper/params_test.go
- x/emissions/types/keys.go
- x/emissions/types/params.go
Rebase `ObserverSlashAmount` fix to develop
> fix: rebase 14.0.1

- changelog.md
- cmd/zetaclientd/start.go
- zetaclient/bitcoin/bitcoin_client.go
- zetaclient/evm/evm_client.go
- zetaclient/metrics/metrics.go
- zetaclient/metrics/telemetry.go
- zetaclient/zetacore_observer.go
As stated in issue, some of the metrics exposed in telemetry server endpoints should be refactored to be prometheus compatible as the other zetaclient metrics.
Moved to metrics:
- number of utxo (from status endpoint) 
- version 
- last start time
- last scanned block number 
- last core block number
Still in telemetry, seems like it is more appropriate than metrics:
- p2p id
- ip address
- hot key burn rate (this is exposed both in metrics and telemetry, but it is stored in telemetry so i left it there)
looks like this:
version (named info so it is same as go_info)
```
zetaclient_info{version="v12.3.0-rc-40-g56c63693"} 1
```
for reference, go_info looks like this:
```
go_info{version="go1.20.14"} 1
```
last start time (using `SetToCurrentTime` from prometheus on zetaclient start)
``` …
```
> refactor: change important metrics on port 8123 to be prometheus compatible

- changelog.md
- zetaclient/evm/evm_signer.go
Changed test eth signer type to support more transaction types. 
Closes: https://github.com/zeta-chain/node/issues/1887
> fix: evm signer tests were failing intermittently in CI 

- .github/workflows/build.yml
- changelog.md
Build and E2E testing CI workflow was only executed for PR to the `develop` branch. This modification allows to run it on any branch so E2E testing can be run when working on release branch (`16.0.0`)
> ci: run E2E tests for all PRs

- changelog.md
- zetaclient/metrics/metrics.go
- zetaclient/tss/tss_keysigns_tracker.go
- zetaclient/tss/tss_keysigns_tracker_test.go
- zetaclient/tss/tss_signer.go
1. Keysign tracker was added to keep track of outbound signature attempts
2. A new metric was integrated to export the number of active signatures. 
Closes: https://github.com/zeta-chain/node/issues/1604
Please describe the tests that you ran to verify your changes. Include instructions and any relevant details so others can reproduce. 
```
/usr/local/bin # curl localhost:8886/metrics | grep zetaclient_num_active_message_signs
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
100 18048    0 18048    0     0  7861k      0 --:--:-- --:--:-- --:--:-- 8812k
zetaclient_num_active_message_signs 4
```
> feat: V16 - add metric for concurrent key signs

- .github/workflows/execute_advanced_tests.yaml
Run some of the advanced tests nightly to detect breakages more quickly. Related to #2054.
I will add slack alerting for failures in a future PR.
I tested that workflow_dispatch [still works](https://github.com/zeta-chain/node/actions/runs/8789497964) and `actionslint` passes.
> test: run advanced tests nightly to detect breakages

- .github/workflows/execute_advanced_tests.yaml
Both the admin tests and upgrade tests are currently failing on develop, but have a green check on github. Examples:
- https://github.com/zeta-chain/node/actions/runs/8740792255/job/23985274941
- https://github.com/zeta-chain/node/actions/runs/8789497964/job/24119390065
We need the github actions run to fail so we can properly track pass/fail rate and add slack notifications.
Ensure that we fail the github actions step by checking the docker container code via `docker wait`. Also:
- create an output group with the `make start-...` to reduce the noise
- stream the test log output
- remove `shell` option since we can tolerate `sh` again. By setting `shell` you clobber the `-e` option which means that errors will silently be ignored.
Example: …
> test: ensure advanced tests fail if orchestrator fails

- changelog.md
- cmd/zetae2e/local/local.go
- e2e/e2etests/e2etests.go
- e2e/e2etests/test_zeta_deposit.go
- x/crosschain/keeper/process_outbound_test.go
- x/fungible/keeper/zevm_message_passing_test.go
- x/fungible/keeper/zevm_msg_passing.go
Automatically deposit native zeta to an address if it doesn't exist on ZEVM. 
Closes: https://github.com/zeta-chain/node/issues/2075
> refactor: allow zeta deposits to new zevm address

- .github/workflows/build.yml
- .github/workflows/execute_advanced_tests.yaml
Add slack notifications for nightly advanced e2e failures and e2e failures when merging develop to the `#alerts-protocol-ci` internal slack channel.
Example run: https://github.com/zeta-chain/node/actions/runs/8835882224/job/24261134350
> ci: add slack notifications nightly/develop failures

- Dockerfile-upgrade
- app/setup_handlers.go
- changelog.md
- cmd/zetae2e/local/local.go
- contrib/localnet/orchestrator/start-zetae2e.sh
- contrib/localnet/scripts/start-zetaclientd.sh
- e2e/utils/zetacore.go
- zetaclient/zetabridge/zetacore_bridge.go
https://github.com/zeta-chain/node/pull/2051 was merged to the wrong branch following the new naming standard for release branches
- Cherry pick changes from to the new release branch.
- Set `v16.0.0`in the changelogs
> test(e2e): fix local e2e upgrade test

- Dockerfile-upgrade
- Makefile
- contrib/localnet/scripts/start-zetacored.sh
Optimize the upgrade image build by using a multi-stage build. Now you can make incremental changes without having to fully rebuild the old version every time. Also mount the go cache directory like #2049 to improve incremental build times.
Relates to DEVOP-643 DEVOP-642
> test: optimize upgrade test image build

- docs/development/DEPLOY_NODES.md
- docs/development/LOCAL_TESTING.md
- docs/development/RELEASES.md
- readme.md
Make a Readme more straightforward and put specific docs (testing, release, node deployment) in their own files
Add also some other fixes in the readme
Closes: https://github.com/zeta-chain/node/issues/1964
> docs: make readme shorter and put specific docs in specific files

- changelog.md
- zetaclient/bitcoin/bitcoin_client.go
- zetaclient/evm/evm_client.go
Removed a few unused variables and the old method `IsSendOutTxProcessed` which was accidentally rolled back by https://github.com/zeta-chain/node/pull/2032
Closes: 
> chore: remove unused variable and method

- .github/workflows/build.yml
Adjust the docker login conditional again to actually fix forks.
If we want the workflows to be run by external people, we should not use the buildjet runners. [github did recently upgrade the free runners for opensource projects btw](https://github.blog/2024-01-17-github-hosted-runners-double-the-power-for-open-source/)
You cannot test the presence of secrets in if statements btw.
> fix: adjust docker login conditional

- changelog.md
- x/crosschain/keeper/process_outbound_test.go
- x/crosschain/keeper/processs_outbound.go
- Add check to revert only ZETA-type transactions.
- Other txs origination from Zetachain are aborted if they revert 
Closes: https://github.com/zeta-chain/node/issues/2159
Note : This also would need to develop
> refactor: limit zevm revert to cointType Zeta

- changelog.md
- x/crosschain/keeper/process_outbound_test.go
- x/crosschain/keeper/processs_outbound.go
- Add check to revert only ZETA-type transactions.
- Other txs origination from Zetachain are aborted if they revert
Closes: https://github.com/zeta-chain/node/issues/2159
Backports: https://github.com/zeta-chain/node/pull/2160
> refactor: add cointype check for zevm revert

- app/app.go
- app/setup_handlers.go
- app/upgrade_tracker.go
- app/upgrade_tracker_test.go
When we start deploying every change from develop on "developnet", we will need the ability to run each store upgrade/migration function individually as the are added.
Introduce the upgrade version tracker which will manage tracking these upgrades. You must now assign a monotonically increasing index for each store upgrade. We store the maximum index on the disk and skip any store upgrades with indexes less than the stored value.
This tracker is only fully used when you explicitly enable it via environment variable. Otherwise, we assume you're doing a major version upgrade (v14 -> v16) and apply all upgrades.
Blocked by resolution of #2077. Update: I am fixing that in this PR too.
Part of DEVOP-642
developnet will be a stateful network where every change from develop is automatically …
> feat(zetacore): add upgrade tracker

- .github/actions/install-dependencies/action.yml
- .github/actions/set-branch-name/action.yml
- .github/actions/upgrade-testing/action.yml
- .github/workflows/build.yml
- .github/workflows/change-log-check.yml
- .github/workflows/docker-build-and-push.yml
- .github/workflows/execute_advanced_tests.yaml
- .github/workflows/generate-files.yml
- .github/workflows/publish-release.yml
- .github/workflows/rc-release.yml
- .github/workflows/sast-linters.yml
- .github/workflows/upgrade_path_testing.yaml
Upgrade github actions workflow dependencies to fix this warning:
> Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/checkout@v3, actions/setup-go@v4, nick-fields/retry@v2.
> chore(ci): upgrade github actions dependencies

- .github/workflows/build.yml
- contrib/localnet/scripts/start-upgrade-orchestrator.sh
- build on ubuntu 20.04 for lower glibc version (related to #2175)
- parameterize upgrade orchestrator binary urls and allow overriding
- follow redirects when downloading binary to get version
Relates to DEVOP-642
> chore: updates for developnet

- changelog.md
- e2e/e2etests/helper_bitcoin.go
- e2e/e2etests/test_bitcoin_withdraw_invalid_address.go
- e2e/e2etests/test_bitcoin_withdraw_legacy.go
- e2e/e2etests/test_bitcoin_withdraw_p2sh.go
- e2e/e2etests/test_bitcoin_withdraw_p2wsh.go
- e2e/e2etests/test_bitcoin_withdraw_segwit.go
- e2e/e2etests/test_bitcoin_withdraw_taproot.go
- e2e/e2etests/test_crosschain_swap.go
- e2e/runner/bitcoin.go
- pkg/chains/bitcoin.go
- pkg/chains/bitcoin_test.go
Removed hard-coded bitcoin chainID in E2E withdraw tests.
> fix: removed hard-coded bitcoin Regnet chainID in E2E withdraw tests

- contrib/localnet/docker-compose-upgrade.yml
- contrib/localnet/scripts/start-zetaclientd.sh
- contrib/localnet/scripts/start-zetacored.sh
On the zetacored containers, test if the `~/.zetacored/init_complete` file exists and skip initialization if it does.
On the zetaclientd containers, test if the `~/.zetacored/config/zetaclient_config.json` file exists and skip initialization if it does.
I need to fully separate setup and test steps in zetae2e in the orchestrator but I will do that in a separate PR.
Relates to #2232
Relates to DEVOP-642
```
make start-localnet
docker stop zetacore1
docker stop zetaclient1
make start-localnet
```
> feat: enable restarting localnet containers

- changelog.md
- typescript/crosschain/genesis_pb.d.ts
- x/crosschain/types/cctx_test.go
- x/crosschain/types/genesis.pb.go
- x/crosschain/types/inbound_params.go
- x/crosschain/types/inbound_params_test.go
- x/crosschain/types/outbound_params.go
- x/crosschain/types/outbound_params_test.go
Porting https://github.com/zeta-chain/node/pull/2237 to a v17 release
Prevent inbound validation to fail for BSC chains
> fix(v17): inbound and outbound validation for BSC chain

- app/setup_handlers.go
We need to upgrade athens to v17 but not run the migrations. You must define a upgrade handler for any upgrades run via upgrade proposals. Define a no-op `v17-athens` handler.
> SetUpgradeHandler sets an UpgradeHandler for the upgrade specified by name. This handler will be called when the upgrade with this name is applied. In order for an upgrade with the given name to proceed, a handler for this upgrade must be set even if it is a no-op function.
Upgrade proposal will be called `v17-athens`
Related to #2228
> feat: add no-op v17 athens upgrade handler

- changelog.md
- zetaclient/chains/bitcoin/observer/live_test.go
- zetaclient/chains/bitcoin/observer/observer.go
- zetaclient/chains/bitcoin/observer/outbound.go
During Bitcoin withdraw tests in Athens3, I noticed an old issue that existed since `v1`. Looking at this mainnet bitcoin outbound cctx:
https://zetachain.blockpi.network/lcd/v1/public/zeta-chain/crosschain/cctx/8332/200
The cctx's outbound parameter contains a wrong `"outbound_tx_observed_external_height": "578"`, the correct height should be `835053` in [bitcoin explorer](https://mempool.space/tx/b41242d2d1e8b63b2ffca88a02f57726a0710753a88e258c45d7edca6f904211)
It is a minor issue that could impact explorer, nothing about security.
> fix: incorrect bitcoin outbound height

- Dockerfile-upgrade
Upgrade tests are failing on release/v17 branch: https://github.com/zeta-chain/node/actions/runs/9214972522/job/25352337296
I forgot to set this in #2231
> fix: set upgrade test new version to v17

- contrib/localnet/orchestrator/start-zetae2e.sh
https://github.com/zeta-chain/node/pull/2264 broke the performance tests:
```
unknown command "local --test-performance" for "zetae2e"
```
This is because of the double quotes, forcing the `local --test performance` args be passed as `os.Args[1]` rather than `os.Args[1:3]`
> fix: remove quotes from e2e args

- .github/ISSUE_TEMPLATE/syncing.yaml
An easy to use form for node operators to fill out if they have issues with setting up or syncing a node.
> chore: add an issue form template for setting up a node

- .github/ISSUE_TEMPLATE/syncing.yaml
- changelog.md
Add question to Node Syncing Issue form - Did you build your binary locally or download it from the Releases[Add_link] page?
Part of: https://github.com/zeta-chain/docs/issues/358
> chore: Update syncing issue form

- cmd/zetae2e/balances.go
- cmd/zetae2e/bitcoin_address.go
- cmd/zetae2e/config/config.go
- cmd/zetae2e/local/accounts.go
- cmd/zetae2e/local/admin.go
- cmd/zetae2e/local/erc20.go
- cmd/zetae2e/local/local.go
- cmd/zetae2e/local/test_runner.go
- cmd/zetae2e/run.go
- cmd/zetae2e/setup_bitcoin.go
- cmd/zetae2e/show_tss.go
- cmd/zetae2e/stress.go
- contrib/localnet/docker-compose-admin.yml
- contrib/localnet/scripts/start-zetacored.sh
- e2e/e2etests/e2etests.go
- e2e/e2etests/test_migrate_chain_support.go
- e2e/runner/runner.go
- e2e/txserver/zeta_tx_server.go
#2308 is getting a bit large, so I'm gonna start breaking stuff out of it.
- use private key rather than pneumonic for fungible admin
- remove fungible admin parameters from e2e instead provide an optional `ZetaTxServer` 
- only populate the `ZetaTxServer` when it's actually needed (admin tests)
Part of https://github.com/zeta-chain/node/issues/2238
> refactor(e2e): use private key rather than mnemonic in admin tests

- cmd/zetaclientd/gen_pre_params.go
Partially backport https://github.com/zeta-chain/node/pull/2353 to fix:
```
➜  ~ docker logs zetaclient0
Error: unknown command "gen-pre-params" for "zetaclientd"
Run 'zetaclientd --help' for usage.
```
which will cause increased failure rates in the upgrade tests. No release is required.
> chore: backport zetaclient gen-pre-params command

- changelog.md
- e2e/runner/bitcoin.go
This PR is to fix below random failure of e2e test `test_crosschain_swap`. The error below was caused by tiny UTXO being used in test.
Closes: #2356
> fix: resolve random failure of cross-chain swap E2E test

- .github/workflows/sast-linters.yml
- changelog.md
This PR is designed to prevent the nosec use scanning workflow from triggering on its own file. It also will only trigger on the addition of `nosec` rather than the removal of it.
This PR changes only the bare minimum needed to resolve the the issues, and could instead be expanded to exempt well known out of scope file extensions.
Changes: 
- Exclude .github/workflows/sast-linters.yml from scanning itself or changelog.md for the presence of the string "nosec"
- Grep only for diff lines which start with '+' and contain nosec
Closes:  https://github.com/zeta-chain/node/issues/1489
> ci: Update sast-linters.yml

- .github/CODEOWNERS
Add fbac as CODEOWNER.
Fixes https://github.com/zeta-chain/node/issues/2409
> chore: add fbac as codeowner

- .github/workflows/build.yml
Add build caching to the e2e build:
- [cache container layers in the registry](https://docs.docker.com/build/ci/github-actions/cache/#registry-cache)
- [inject go build cache](https://github.com/reproducible-containers/buildkit-cache-dance)
Only populate the cache on the push event. On a cache hit, this should reduce runtimes by about ~2 minutes ([example](https://github.com/gartnera/node/actions/runs/9737295434/job/26870606140))
> ci: add build cache to e2e

- zetaclient/config/config.go
I missed this change when I was partially backporting https://github.com/zeta-chain/node/pull/2353 in https://github.com/zeta-chain/node/pull/2363. 
This results in errors like this:
```
2024-07-02T23:17:47Z ERR open pre-params file failed; skip error="open root/preparams/zetaclient0.json: no such file or directory"
```
which means a new pre-params file will have to be generated at start rather than init resulting in a greater chance of missing the keygen block.
> fix(zetaclient): tolerate absolute path in GetPath()

- .github/workflows/build.yml
- .github/workflows/e2e.yml
- .github/workflows/generate-files.yml
- .github/workflows/sast-linters.yml
Add [merge_group](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#merge_group) triggers to all required workflows. All required status checks must be reported when using merge queue.
Run the light upgrades tests on mergequeue. This means that the upgrade tests will have to pass before merge. Update: the upgrade tests are not stable right now, let's just run default e2e for now.
Once this is approved, I will enable [merge queue](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue) and this will be the first PR to merge via merge queue.
Related to #2134
> ci: add merge_group triggers

- Makefile
- cmd/zetae2e/local/local.go
- cmd/zetae2e/local/v2.go
- e2e/e2etests/e2etests.go
- e2e/e2etests/test_v2_erc20_deposit.go
- e2e/e2etests/test_v2_erc20_deposit_and_call.go
- e2e/e2etests/test_v2_erc20_withdraw.go
- e2e/e2etests/test_v2_erc20_withdraw_and_call.go
- e2e/e2etests/test_v2_eth_deposit.go
- e2e/e2etests/test_v2_eth_deposit_and_call.go
- e2e/e2etests/test_v2_eth_withdraw.go
- e2e/e2etests/test_v2_eth_withdraw_and_call.go
- e2e/e2etests/test_v2_evm_to_zevm_call.go
- e2e/e2etests/test_v2_zevm_to_evm_call.go
- e2e/runner/v2_evm.go
- e2e/runner/v2_zevm.go
Add the body for the v2 smart contract E2E tests to the contract-v2 feature branch.
```
/*
V2 smart contract tests
*/
TestV2ETHDepositName           = "v2_eth_deposit"
TestV2ETHDepositAndCallName    = "v2_eth_deposit_and_call"
TestV2ETHWithdrawName          = "v2_eth_withdraw"
TestV2ETHWithdrawAndCallName   = "v2_eth_withdraw_and_call"
TestV2ERC20DepositName         = "v2_erc20_deposit"
TestV2ERC20DepositAndCallName  = "v2_erc20_deposit_and_call"
TestV2ERC20WithdrawName        = "v2_erc20_withdraw"
TestV2ERC20WithdrawAndCallName = "v2_erc20_withdraw_and_call"
TestV2ZEVMToEVMCallName        = "v2_zevm_to_evm_call"
TestV2EVMToZEVMCallName        = "v2_evm_to_zevm_call"
```
Add makefile command:
```
make start-v2-test
```
This will allow to test the features live. Right now the tests will …
> feat(E2E): add body for smart contract V2 tests

- cmd/zetae2e/local/local.go
- e2e/e2etests/e2etests.go
- e2e/e2etests/test_whitelist_erc20.go
- x/crosschain/keeper/msg_server_whitelist_erc20.go
v19 backport for https://github.com/zeta-chain/node/pull/2631
> fix(crosschain): set sender for ERC20 whitelist admin CCTX inbound (v19 backport)

- Makefile
* Update golang cross compile to 1.22.4
* update deprecated --skip-validate --skip-release flags
(cherry picked from commit 5dd6fd66354a6b43d036b8c3c07f5580b0c6a9ae)
Tested by @CharlieMc0 locally
> fix(ci): Update golang cross compile to 1.22.4 (#2635)

- .goreleaser.yaml
- app/setup_handlers.go
- contrib/localnet/scripts/start-upgrade-orchestrator.sh
- version.sh
Backport https://github.com/zeta-chain/node/pull/2646
Also explicitly set upgrade handler version to `v19` to stay consistent with previous upgrades
> fix(ci): use FullCommit and align version logic

- changelog.md
- contrib/localnet/orchestrator/start-zetae2e.sh
- zetaclient/zetacore/client.go
- zetaclient/zetacore/tx_test.go
API `GetBlockHeaderEnabledChains` is not working in `v19.0.0`. Bypass the query so that `zetaclientd` can start well.
> fix: skip calling 'GetBlockHeaderEnabledChains()' to bypass API error

- changelog.md
- go.sum
- zetaclient/evm/evm_client.go
- zetaclient/evm/evm_signer.go
Cherry picked minimum fix from [the PR](https://github.com/zeta-chain/node/pull/2628):
> fix: do not submit pending hash to tracker to avoid invalid hash

- .github/workflows/publish-release.yml
Backport https://github.com/zeta-chain/node/pull/2733 to release/v19. I will cut v19.1.1 after this.
> ci: use large runner for release (#2733)

- changelog.md
- zetaclient/chains/bitcoin/observer/inbound.go
- zetaclient/chains/bitcoin/observer/inbound_test.go
- zetaclient/chains/bitcoin/observer/witness_test.go
> refactor(observer): disable Bitcoin witness support for mainnet (release/v20)

- .github/workflows/publish-release.yml
- Makefile
- app/setup_handlers.go
- contrib/localnet/scripts/import-data.sh
- contrib/localnet/scripts/start-upgrade-orchestrator.sh
Should get the mainnet upgrade tests passing again
> chore: backport upgrade/ci changes for v20

- zetaclient/orchestrator/orchestrator.go
> fix: move schedule interval calculation out of the loop (release v20)

- Makefile
The `old-runtime` target in the docker build in the`zetanode-upgrade` make target depends on `latest-runtime` docker target so we need to also set the NODE_VERSION and NODE_COMMIT to ensure that there is not a pointless rebuild:
<details>
```
#27 [latest-build 6/6] RUN --mount=type=cache,target="/root/.cache/go-build"     NODE_VERSION=${NODE_VERSION}     NODE_COMMIT=${NODE_COMMIT}     make install install-zetae2e
#27 0.168 fatal: not a git repository (or any of the parent directories): .git
#27 0.169 fatal: not a git repository (or any of the parent directories): .git
#27 0.170 warning: Not a git repository. Use --no-index to compare two paths outside a working tree
#27 0.170 usage: git diff --no-index [<options>] <path> <path>
#27 0.170 
#27 0.170 Diff output format options
#27 0.170 …
```
> fix: ensure NODE_VERSION and NODE_COMMIT are set for upgrade builds

- go.mod
- go.sum
Uses this commit: https://github.com/zeta-chain/go-tss/commit/f4e1f77ec1425d8391cfd89a3932db50ad4ea229
Removing dht to disable discovery.
> fix: bump go tss to remove dht

- go.mod
- go.sum
Reverts zeta-chain/node#3032 and restores changes to remove DHT completely
> fix: Revert "fix: stop dht after 5min"

- app/setup_handlers.go
- contrib/localnet/scripts/start-upgrade-orchestrator.sh
Set explicit upgrade handler version for v21 like we did in v20
> chore: set v21 upgrade version

- cmd/zetae2e/local/local.go
- e2e/e2etests/test_precompiles_bank.go
- precompiles/precompiles.go
> refactor: disable precompiles

- testutil/keeper/mocks/fungible/bank.go
- x/fungible/keeper/deposits_test.go
- x/fungible/keeper/zeta.go
- x/fungible/keeper/zeta_test.go
- x/fungible/keeper/zevm_message_passing_test.go
- x/fungible/types/errors.go
- x/fungible/types/expected_keepers.go
Add a check for ZETA deposit to not surpass a supply cap as an extra security check
> refactor: improve ZETA deposit check with max supply check (v21 backport)

- testutil/keeper/mocks/fungible/bank.go
- x/fungible/keeper/deposits_test.go
- x/fungible/keeper/zeta.go
- x/fungible/keeper/zeta_test.go
- x/fungible/keeper/zevm_message_passing_test.go
- x/fungible/types/errors.go
- x/fungible/types/expected_keepers.go
This reverts commit 70a0e40373e9f3a3c707f79f7b47b95dd4289c97.
Revert https://github.com/zeta-chain/node/pull/3073 on v21 in preparation for v22 branch
> chore: revert "refactor: max supply check (#3073)"

- testutil/keeper/mocks/fungible/bank.go
- x/fungible/keeper/deposits_test.go
- x/fungible/keeper/zeta.go
- x/fungible/keeper/zeta_test.go
- x/fungible/keeper/zevm_message_passing_test.go
- x/fungible/types/errors.go
- x/fungible/types/expected_keepers.go
> revert: `refactor: improve ZETA deposit check with max supply check`

- cmd/zetae2e/local/local.go
- e2e/e2etests/e2etests.go
- e2e/e2etests/test_bitcoin_deposit_and_call_revert.go
- e2e/e2etests/test_bitcoin_deposit_and_call_revert_with_dust.go
- zetaclient/chains/bitcoin/observer/outbound.go
- zetaclient/chains/bitcoin/signer/signer.go
Check if the amount for a BTC revert outbound is below dust amount. In this case, cancel the tx (same logic as restricted address where there will be a tx but with 0 btc), cctx will be reverted.
Add a E2E test to test revert with dust amount. To check the effect, the "dustAmount" can be set to false in ZetaClient, the test will be stall because the outbound can't be signed
> fix: allow BTC revert with dust amount v22

- zetaclient/zetacore/client_monitor.go
- zetaclient/zetacore/constant.go
Backport https://github.com/zeta-chain/node/pull/3144 to v22
> fix: out of gas on ZetaClient during `onRevert` (v22 backport)

- changelog.md
- go.mod
- go.sum
Backport https://github.com/zeta-chain/node/pull/3171
> fix(zetaclient): infinite discovery address leak (v22)

- changelog.md
- cmd/zetaclientd/start.go
Backport https://github.com/zeta-chain/node/pull/3181
> fix(zetaclient): lock pingRTT for writing (#3181)

- cmd/zetaclientd/start.go
- go.mod
- go.sum
- zetaclient/tss/tss_signer.go
V22.1.2 is causing signing to stop on testnet. Revert go-tss to v21/v22 version.
> chore: revert go-tss to v21/v22 version

- zetaclient/chains/evm/observer/inbound.go
- zetaclient/chains/evm/observer/v2_inbound_tracker.go
Backport changes from https://github.com/zeta-chain/node/pull/3226 (only ZetaClient changes)
> fix: allow processing v2 inbound trackers for gateway calls initiated by smart contracts (v2 backport)

- zetaclient/chains/solana/observer/inbound_tracker.go
- zetaclient/chains/solana/rpc/rpc.go
- zetaclient/chains/solana/rpc/rpc_live_test.go
Athens is blocked by below RPC query error. This is because the function `GetSignaturesForAddressUntil` now only works when the passed `untilSig` argument is a legacy transaction. It returns error if `untilSig` is a version "0" tx and blocks inbound observation.
```
error GetTransaction for untilSig 39fSgD2nteJCQRQP3ynqEcDMZAFSETCbfb61AUqLU6y7qbzSJL5rn2DHU2oM35zsf94Feb5C5QWd5L5UnncBsAay: (*jsonrpc.RPCError)(0x40006de030)({
Code: (int) -32015,
Message: (string) (len=175) "Transaction version (0) is not supported by the requesting client. Please try the request again with the following configuration parameter: \"maxSupportedTransactionVersion\": 0",
Data: (interface {}) <nil>
})
```
> fix: query solana inbound signatures using max version0 to avoid errors

- zetaclient/chains/solana/signer/signer.go
- zetaclient/keys/relayer_key.go
Move the relayer key existence checking after TSS keysign so that all tss signers can continue scheduling keysign without a configured Solana relayer key.
> fix: move relayer key check after tss keysign

- pkg/contracts/solana/inbound_test.go
- zetaclient/chains/evm/observer/inbound.go
- zetaclient/chains/evm/observer/inbound_test.go
- zetaclient/chains/evm/observer/v2_inbound.go
ERC20 deposits were not well observed in BSC, Polygon. These were caused by foreign coin asset mismatch in the `MsgVoteInbound`. See:
BSC failed vote: https://explorer.zetachain.com/cosmos/tx/5F81D3F623B57E64FBF4ADE684C778BF83ACA8AC059A86B7D2273908930A2022
Polygon failed vote: https://explorer.zetachain.com/cosmos/tx/1C54E4CAFBE226B17E82D838291DF65EF51EE07EDCFD2B7DDE39EA735E7FAC67
Solution:
Taking the [list of foreign ERC20 tokens](https://zetachain.blockpi.network/lcd/v1/public/zeta-chain/fungible/foreign_coins), and hardcoded the mapping `ERC20 address --> asset` so that zetaclients can use the correct asset string in their inbound ERC20 votes.
> fix: hardcode erc20 asset strings to align with the data in foreign coin store

- pkg/fanout/fanout.go
- pkg/fanout/fanout_test.go
- zetaclient/zetacore/client.go
- zetaclient/zetacore/client_subscriptions.go
Apply block subscriber fanout fix from https://github.com/zeta-chain/node/pull/3332
> Found the issue: cosmos WS client doesn't support multiple subscription channels per event. So if we have multiple zetacoreClient.NewBlockSubscriber(ctx), the latter hijacks all block updates. I'll implement fan-out pattern to ensure we have only 1 connection
> fix: ensure block subscriptions do not conflict (v25)

- app/app.go
- changelog.md
Set the per-transaction gas limit so that the 99.9th-percentile transaction is allowed, but the maximum gas-value transaction is not. A limit of 10M is significantly higher than the 99.9th-percentile value to avoid disrupting legitimate transactions.
This will ensure that ridiculously large transactions do not degrade the network performance.
Will backport to develop.
> fix!: set per transaction gas limit to 10M

- e2e/e2etests/e2etests.go
- e2e/runner/e2etest.go
- e2e/runner/run.go
- e2e/runner/runner.go
Add optional minimum version parameter to e2e tests. If this constraint is not satisfied, the test will be skipped. This allows you to introduce new/breaking content without breaking the upgrade tests. The test will start running during upgrades after the release that exceeds the minimum version. We always run all test on development versions (`v0.0.x`).
Example:
```
v2-eth-rever | ✅ completed - eth_withdraw_and_call_revert_with_call (duration 18.611013727s)
v2-eth-rever | ⚠️ skipping  - eth_withdraw_and_call_revert_with_withdraw (minimum version v26.0.0)
v2-eth-rever | ⏳ running   - deposit_and_call_out_of_gas
```
The test will still run on the second run after the upgrade has completed.
This test is what is causing the nightly upgrade failures. Related to …
> feat(e2e): add optional minimum version to test

- changelog.md
- pkg/rpc/clients_crosschain.go
- zetaclient/chains/bitcoin/bitcoin.go
- zetaclient/chains/evm/evm.go
- zetaclient/chains/interfaces/interfaces.go
- zetaclient/chains/solana/solana.go
- zetaclient/chains/ton/ton.go
- zetaclient/testutils/mocks/zetacore_client.go
- zetaclient/zetacore/client_crosschain.go
Backport #3484 and prepare v27.0.2 release
> fix(zetaclient): use chain name in metrics (#3484)

- changelog.md
- zetaclient/chains/evm/observer/inbound.go
This PR takes a hatchet to zetaclient/chains/evm/observer/inbound.go to validate the expected gains from not observing TSS direct transfers on Arbitrum and Avalanche.
> fix: skip block scanning actions on Arbitrum and Avalanch networks (v27)

- changelog.md
- zetaclient/chains/base/observer.go
- zetaclient/chains/base/observer_test.go
- zetaclient/chains/evm/observer/inbound_test.go
- zetaclient/chains/interfaces/interfaces.go
- zetaclient/chains/ton/observer/inbound_test.go
- zetaclient/chains/ton/observer/observer_test.go
- zetaclient/testutils/mocks/zetacore_client.go
- zetaclient/testutils/mocks/zetacore_client_opts.go
Closes : https://github.com/zeta-chain/node/issues/3635
The pr adds a check to stop zetaclient from voting on unnecessary ballots.
For e2e testing, its not straightforward to add a test , as we only print to logs when not casting votes.This has been tested manually by creating a tracker with the details from a confirmed CCTX and checking zetalient logs.
> fix: check if cctx has already been created before casting inbound vote

- zetaclient/chains/evm/common/constant.go
Background:
The error below has been blocking Arbitrum gas token withdraw.
Not all EVM chains use the same `21000` gas limit for gas token transfers, e.g. `Arbitrum` could uses `24000+` gas for ETH transfer. The PR increases the static gas limit `21000 -> 25000` to make it working for all EVM chains.
> fix: increase gas token withdraw gas limit for EVM chain

- zetaclient/chains/evm/common/constant.go
This PR ports this v28 [Arbitrum withdraw fix](https://github.com/zeta-chain/node/pull/3667) to v29
> fix: port the v28 Arbitrum withdraw fix to v29

- changelog.md
- zetaclient/chains/solana/signer/signer.go
Every zetaclient is doing key sign and  then relayer sign, even though they might not have relayer key. This was causing panics from the start of solana outbounds, but not causing outbounds to fail because panics were recovered and relayer broadcasted it.
But now we might have 2 key signs, tx and fallback tx, so if there is panic after key sign for tx, fallback tx keysign will always fail.
This PR is simplest fix for this, for next milestone we can refactor it to be a bit more cleaner and less code duplication, but just skipping relayer sign should be enough if key is not set up.
> fix: fix solana withdraw and call outbounds

- zetaclient/chains/evm/signer/gas.go
- zetaclient/zetacore/constant.go
V29 backport for https://github.com/zeta-chain/node/pull/3719
> fix: add min gas limit for non-gas outbound transactions (v29 backport)

- e2e/e2etests/test_bitcoin_deposit_invalid_memo_revert.go
- e2e/runner/bitcoin.go
- zetaclient/chains/bitcoin/observer/event.go
- zetaclient/chains/bitcoin/observer/event_test.go
- zetaclient/chains/bitcoin/observer/inbound_test.go
- zetaclient/chains/bitcoin/observer/witness.go
- zetaclient/chains/bitcoin/observer/witness_test.go
The v29 is able to revert Bitcoin deposits that carry incorrectly formatted memo (e.g., invalid receiver address), but it cannot properly revert deposits that carry no memo at all, which are supposed be reverted.
This fix will allow no-memo deposits to be able to go through ZetaChain and get funds reverted.
> fix: revert Bitcoin inbound if there no memo provided by user

- cmd/zetatool/config/config.go
- zetaclient/chains/bitcoin/observer/inbound.go
Add additional log prints to debug the reason of missed Testnet4 inbounds.
> test: add btc inbound logs to find root cause of Testnet4 missed txs

- changelog.md
- e2e/e2etests/test_sui_withdraw.go
- pkg/contracts/sui/crypto.go
- pkg/contracts/sui/crypto_test.go
- zetaclient/chains/sui/signer/signer_tx.go
If the withdraw address is invalid, the ZetaClient sign the tx to the TSS, this is like a donation to the TSS.
A fix in the main branch will make the withdraw revert instead
> fix: prevent invalid Sui withdraw address from blocking the outbound

- zetaclient/chains/evm/observer/outbound.go
- zetaclient/chains/solana/observer/outbound.go
- zetaclient/chains/sui/observer/outbound.go
- zetaclient/chains/ton/observer/outbound.go
- zetaclient/zetacore/constant.go
Currently if outbound is successful retry gas limit will be 0, meaning there won't be retry for voting if 500k is not enough.
This introduces retry gas limit 1M for all observers.
> fix: set retry gas limit if outbound is successful

- pkg/contracts/sui/gateway.go
- pkg/contracts/sui/gateway_test.go
Backport for https://github.com/zeta-chain/node/pull/3915 to v30
> fix(backport/v30): add support for non-base64 formatted payload in Sui DepositAndCall event parsing 

- zetaclient/chains/evm/observer/observer_gas.go
- zetaclient/chains/evm/observer/observer_gas_test.go
The Base mainnet CCTX outbound keeps failing. Most likely the gas price in the [CCTX](https://zetachain.blockpi.network/lcd/v1/public/zeta-chain/crosschain/gasPrice/8453) is too low. The outbound tx is dropped by the endpoint right after broadcasting.
We rely on the gas stability pool to increase CCTX's gas price but the gas bumping logic fails due to below error. The fix is to post `zero` priority fee to avoid this failure and allow gas stability pool to kick in.
> fix: post zero priority fee to avoid gas price bump failure in zetacore

- cmd/zetae2e/local/local.go
- e2e/e2etests/e2etests.go
- e2e/e2etests/test_sui_withdraw_invalid_receiver.go
- zetaclient/chains/sui/signer/signer.go
- zetaclient/chains/sui/signer/signer_test.go
This PR is to unblock any future CCTXs that contain invalid Sui receiver addresses.
Here is an example CCTX in the history: https://zetachain-testnet-api.itrocket.net/zeta-chain/crosschain/cctx/103/215
> fix: revert sui CCTX that contains invalid receiver address

- Makefile
- changelog.md
- e2e/e2etests/e2etests.go
- go.mod
- go.sum
> chore: upgrade cosmos sdk to 0.50.14

- changelog.md
- zetaclient/chains/sui/observer/observer_test.go
- zetaclient/chains/sui/observer/outbound.go
- zetaclient/chains/ton/observer/inbound.go
- zetaclient/chains/ton/observer/outbound.go
Fix the invalid Sui minting for the gas stability pool when doing Sui outbounds
Effective gas limit to fund gas stability pool which is not used for Sui and TON
> fix: use 0 for effective gas limit for Sui and TON

- e2e/e2etests/e2etests.go
- e2e/e2etests/test_solana_withdraw_and_call_invalid_tx_size.go
- zetaclient/chains/solana/signer/fallback_tx.go
- zetaclient/chains/solana/signer/fallback_tx_test.go
Cancel Solana withdrawAndCall if the outbound tx size is too large. Here is an example error:
> fix: cancel solana WaC if tx size is too large

- app/app.go
fixes error
```
"rpc error: code = Internal desc = runtime error: invalid memory address or nil pointer dereference"
```
issue is that native tracers are registered in `init` function in go-ethereum native tracers package, so package should be imported somewhere to force registration
this makes callTracer working, for some reason i can't import js tracers, but for now this should be good enough
> fix: nil reference in trace block

- go.mod
- go.sum
bump cosmos evm to support querying legacy proposals of type MsgUpdateParams
https://github.com/zeta-chain/evm/pull/6
> chore : bump cosmos evm to support querying legacy proposals of type MsgUpdateParams 

- server/start.go
- server/timeout.go
- server/timeout_test.go
- Remove restrictions for mainnet, and instead use the value of ` --skip-config-overwrite` flag directly
- Remove logic to write the config back to the filesystem
> fix: skip writing config file to the filesystem
